### ISSUE TITLE
Generated script from Web App is not conform

### ISSUE THREAD

**Issue by MathieuSoysal** [CodeIntelligenceTesting/github-actions#7]
## Introduction

Currently, I'm working on https://github.com/MathieuSoysal/Kata-Datanumia , and I'm trying to implement the fuzzing testing of CIFuzz.

## Problem

But I have a warning when I want to use the generated script CI (for GitHub Actions) from https://app.code-intelligence.com/dashboard/projects , the generated script is not confirmed because the `project` attribute (a required attribute) is not contained inside these lines :

```yml
      - id: start-fuzzing
        name: Start Fuzzing
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v5
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          fuzzing_artifact: ${{ env.CHECKOUT_DIR }}/${{ env.FUZZING_ARTIFACT }}
          checkout_directory: ${{ env.CHECKOUT_DIR }}
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v5
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: save-results
        name: Save Fuzz Test Results
        uses: CodeIntelligenceTesting/github-actions/save-results@v5
        if: ${{ success() || failure() }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
```
